services:
  app:
    container_name: app
    build: .
    restart: on-failure
    ports:
      - '3300:3300'
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./sessions:/usr/src/app/sessions
      - ./src/logs:/usr/src/app/src/logs
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3300/health || exit 1']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
