version: '3.8'

services:
  app:
    container_name: whatsapp_service
    build: .
    restart: on-failure
    ports:
      - '3300:3300'
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - STATIC_API_KEY=${STATIC_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - session_data:/usr/src/app/sessions
      - log_data:/usr/src/app/logs
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3300/health || exit 1']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  session_data:
  log_data:
