services:
  app:
    container_name: whatsapp_service
    build: .
    restart: on-failure
    ports:
      - '3300:3300'
    environment:
      - API_KEY=your_global_api_key_here
      - SET_MESSAGES_AS_SEEN=TRUE
      - DISABLED_CALLBACKS=message_ack|message_reaction
      - ENABLE_SWAGGER_ENDPOINT=TRUE |
    volumes:
      - ./sessions:/usr/src/app/sessions
      - ./logs:/usr/src/app/logs
