const STATUS_CODE = {
  HTTP_SUCCESS: 200,

  HTTP_BAD_REQUEST: 400,
  HTTP_UNAUTHORIZED: 403,
  HTTP_NOT_ALLOWED: 405,
  HTTP_PRECONDITION_FAILED: 412,

  HTTP_INTERNAL_SERVER_ERROR: 500,
  HTTP_SERVICE_UNAVAILABLE: 511,
  HTTP_CLEAN_UP_FAILED: 512
};

Object.freeze(STATUS_CODE);
module.exports = { STATUS_CODE };
